### ISSUE TITLE
[FEATURE] Ability To Toggle the Vuffer Display from "Show" to "Hide"  

### ISSUE THREAD

**Issue by TheCedarPrince** [Hajime-Suzuki/vuffers.nvim#34]
Hi @Hajime-Suzuki ,

I would've opeend this in a discussion but saw I couldn't so thought I would just ask after reading the documentation and source code: is it possible to toggle to show the vuffer display when I want to see it versus hide it? I saw that there was `toggle_auto_resize` but that's not exactly what I am looking for. 

Thanks!

~ tcp :deciduous_tree:

**Comment by Hajime-Suzuki** [comment]
Thank you for asking! There is `toggle` function [here](https://github.com/Hajime-Suzuki/vuffers.nvim/blob/21c17e565847df238ee2d938f181beecfc163ed8/lua/vuffers.lua#L33-L39). Sorry it's not documented in readme, I will update it.

**Comment by TheCedarPrince** [comment]
Ah that worked perfectly! Thank you @Hajime-Suzuki !
