### ISSUE TITLE
[QUESTION] Interoperability with Vim-Obsession?

### ISSUE THREAD

**Issue by TheCedarPrince** [Hajime-Suzuki/vuffers.nvim#35]
Hi @Hajime-Suzuki ,

Do you happen to know if vuffers can be used alongside [vim-obsession](https://github.com/tpope/vim-obsession)? I use it to track and restore sessions with vim and was curious if we could somehow use this alongside vuffers. 

Thanks!

~ tcp :deciduous_tree:

**Comment by Hajime-Suzuki** [comment]
I use [neovim-session-manager](https://github.com/Shatur/neovim-session-manager) and I haven't used `vim-obsession`, but it should work. 

If you use custom display names, please run `on_session_loaded` function when a session is loaded:
```
vim.api.nvim_create_autocmd("SessionLoadPost", {
	callback = function()
		require("vuffers").on_session_loaded()
	end,
})
```
Without it, your custom display names are not restored.

Does vim-obsession restore sessions? By quickly reading its readme I didn't see that.

**Comment by TheCedarPrince** [comment]
Ah I see -- Vim-Obsession actually just tracks sessions to a file consistently. Doesn't really help with session reloading. But the above should work actually for my use case; was a little bit confused. Thanks!
